[project]
name = "medwise-project-114"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2",
    "django-extensions>=4.1",
    "django-ninja>=1.4.1",
    "numpy>=2.2.4",
    "pandas>=2.2.3",
    "pydantic>=2.11.3",
    "requests>=2.32.3",
    "sentence-transformers>=4.1.0",
    "tenacity>=9.1.2",
]
