# Generated by Django 5.2 on 2025-04-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icd_matcher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalAdmissionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_data', models.TextField()),
                ('admission_date', models.DateField()),
                ('predicted_icd_code', models.CharField(blank=True, max_length=20, null=True)),
                ('prediction_accuracy', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medical Admission Detail',
                'verbose_name_plural': 'Medical Admission Details',
                'db_table': 'icd_matcher_medicaladmissiondetails',
            },
        ),
    ]
