# Generated by Django 5.1.7 on 2025-04-08 17:19

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icd_matcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='icdcategory',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='icdcategory',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='icd_matcher_search__51edd6_gin'),
        ),
    ]
