# Generated by Django 5.2 on 2025-04-28 10:24

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icd_matcher', '0002_medicaladmissiondetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaladmissiondetails',
            name='predicted_icd_codes',
            field=jsonfield.fields.JSONField(blank=True, default=list),
        ),
    ]
