# Generated by Django 5.1.7 on 2025-04-08 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icd_matcher', '0002_icdcategory_search_vector_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='icdcategory',
            name='icd_matcher_search__51edd6_gin',
        ),
        migrations.RemoveField(
            model_name='icdcategory',
            name='search_vector',
        ),
    ]
