# Generated by Django 5.1.7 on 2025-04-08 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icd_matcher', '0003_remove_icdcategory_icd_matcher_search__51edd6_gin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icdcategory',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='icdcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icd_matcher.icdcategory'),
        ),
    ]
