# Generated by Django 5.2 on 2025-05-18 14:59

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icd_matcher', '0003_medicaladmissiondetails_predicted_icd_codes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicaladmissiondetails',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='icdcategory',
            name='icd_matcher_code_99c8b7_idx',
        ),
        migrations.RemoveField(
            model_name='medicaladmissiondetails',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='icdcategory',
            name='exclusions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='icdcategory',
            name='inclusions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='medicaladmissiondetails',
            name='predicted_icd_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medicaladmissiondetails',
            name='predicted_icd_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='icdcategory',
            index=models.Index(fields=['code', 'title'], name='icd_matcher_code_b06f23_idx'),
        ),
        migrations.AddIndex(
            model_name='icdcategory',
            index=models.Index(fields=['title'], name='icd_title_idx'),
        ),
        migrations.AddIndex(
            model_name='medicaladmissiondetails',
            index=models.Index(fields=['admission_date'], name='icd_matcher_admissi_a9dd55_idx'),
        ),
        migrations.AddIndex(
            model_name='medicaladmissiondetails',
            index=models.Index(fields=['predicted_icd_code'], name='icd_matcher_predict_614bed_idx'),
        ),
        migrations.AddIndex(
            model_name='medicaladmissiondetails',
            index=django.contrib.postgres.indexes.GinIndex(fields=['predicted_icd_codes'], name='icd_matcher_predict_181ea5_gin'),
        ),
        migrations.AlterModelTable(
            name='medicaladmissiondetails',
            table=None,
        ),
    ]
