# Generated by Django 5.1.7 on 2025-04-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icd_matcher', '0004_alter_icdcategory_code_alter_icdcategory_parent'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='icdcategory',
            index=models.Index(fields=['code'], name='icd_matcher_code_99c8b7_idx'),
        ),
    ]
