# Generated by Django 5.2.1 on 2025-06-09 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icd_matcher', '0004_alter_medicaladmissiondetails_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='icdcategory',
            name='icd_matcher_code_b06f23_idx',
        ),
        migrations.RenameIndex(
            model_name='icdcategory',
            new_name='icd_matcher_title_f5cd06_idx',
            old_name='icd_title_idx',
        ),
        migrations.RemoveField(
            model_name='icdcategory',
            name='id',
        ),
        migrations.AlterField(
            model_name='icdcategory',
            name='code',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='icdcategory',
            name='definition',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='icdcategory',
            name='exclusions',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='icdcategory',
            name='inclusions',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='icdcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='icd_matcher.icdcategory'),
        ),
        migrations.AlterField(
            model_name='icdcategory',
            name='title',
            field=models.TextField(),
        ),
        migrations.AddIndex(
            model_name='icdcategory',
            index=models.Index(fields=['code'], name='icd_matcher_code_99c8b7_idx'),
        ),
    ]
