# Generated by Django 5.2.1 on 2025-07-04 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icd_matcher', '0005_remove_icdcategory_icd_matcher_code_b06f23_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='icdcategory',
            name='icd_matcher_code_99c8b7_idx',
        ),
        migrations.RenameIndex(
            model_name='icdcategory',
            new_name='icd_title_idx',
            old_name='icd_matcher_title_f5cd06_idx',
        ),
        migrations.AddField(
            model_name='icdcategory',
            name='clinical_notes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='icdcategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='icdcategory',
            name='prevalence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icdcategory',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='icdcategory',
            name='definition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icdcategory',
            name='exclusions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='icdcategory',
            name='inclusions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='icdcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icd_matcher.icdcategory'),
        ),
        migrations.AlterField(
            model_name='icdcategory',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='icdcategory',
            index=models.Index(fields=['code', 'title'], name='icd_matcher_code_b06f23_idx'),
        ),
    ]
