# Generated by Django 5.2.1 on 2025-07-04 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icd_matcher', '0006_remove_icdcategory_icd_matcher_code_99c8b7_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='icdcategory',
            name='icd_title_idx',
        ),
        migrations.RemoveIndex(
            model_name='icdcategory',
            name='icd_matcher_code_b06f23_idx',
        ),
        migrations.RemoveField(
            model_name='icdcategory',
            name='clinical_notes',
        ),
        migrations.RemoveField(
            model_name='icdcategory',
            name='prevalence',
        ),
        migrations.AlterField(
            model_name='icdcategory',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='icdcategory',
            name='definition',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='icdcategory',
            name='exclusions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='icdcategory',
            name='inclusions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='icdcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='icd_matcher.icdcategory'),
        ),
    ]
